# Generated by Django 4.0.1 on 2022-01-26 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('album_name', models.CharField(db_index=True, max_length=255)),
                ('album_slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('album_type_1', models.CharField(max_length=255)),
                ('album_type_2', models.CharField(max_length=255)),
                ('album_URL', models.CharField(max_length=255)),
                ('album_release_date', models.DateField(null=True)),
                ('album_total_tracks', models.SmallIntegerField()),
                ('album_image_300', models.CharField(max_length=255)),
                ('album_image_64', models.CharField(max_length=255)),
                ('band_name', models.CharField(max_length=255)),
                ('album_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Альбомов',
                'verbose_name_plural': 'Альбомов',
                'ordering': ('band_name', 'album_release_date', 'album_name'),
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('band_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('band_name', models.CharField(db_index=True, max_length=255)),
                ('band_slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('band_genres', models.CharField(max_length=255)),
                ('band_URL', models.URLField(max_length=255)),
                ('band_followers', models.SmallIntegerField(default=0)),
                ('band_popularity', models.SmallIntegerField(default=0)),
                ('band_image_300', models.CharField(max_length=255)),
                ('band_image_64', models.CharField(max_length=255)),
                ('band_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Групп',
                'verbose_name_plural': 'Групп',
                'ordering': ('band_name',),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('track_name', models.CharField(db_index=True, max_length=255)),
                ('track_slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('track_disc_number', models.SmallIntegerField(default=1)),
                ('track_number', models.SmallIntegerField()),
                ('track_duration', models.IntegerField()),
                ('track_playcount', models.SmallIntegerField(default=0)),
                ('track_listeners', models.SmallIntegerField(default=0)),
                ('album_name', models.CharField(max_length=255)),
                ('band_name', models.CharField(max_length=255)),
                ('track_image_300', models.CharField(max_length=255)),
                ('track_image_64', models.CharField(max_length=255)),
                ('track_preview', models.CharField(max_length=255)),
                ('track_URL', models.CharField(max_length=255)),
                ('track_danceability', models.FloatField(default=0.0)),
                ('track_energy', models.FloatField(default=0.0)),
                ('track_key', models.FloatField(default=0.0)),
                ('track_loudness', models.FloatField(default=0.0)),
                ('track_mode', models.FloatField(default=0.0)),
                ('track_speechiness', models.FloatField(default=0.0)),
                ('track_acousticness', models.FloatField(default=0.0)),
                ('track_instrumentalness', models.FloatField(default=0.0)),
                ('track_liveness', models.FloatField(default=0.0)),
                ('track_valence', models.FloatField(default=0.0)),
                ('track_tempo', models.FloatField(default=0.0)),
                ('track_created', models.DateTimeField(auto_now_add=True)),
                ('album_id', models.ForeignKey(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, related_name='track_by_album', to='tracks.album')),
                ('band_id', models.ForeignKey(db_column='band_id', on_delete=django.db.models.deletion.CASCADE, related_name='track_by_band', to='tracks.band')),
            ],
            options={
                'verbose_name': 'Треков',
                'verbose_name_plural': 'Треков',
                'ordering': ('band_name', 'album_name', 'track_name'),
            },
        ),
        migrations.AddField(
            model_name='album',
            name='band_id',
            field=models.ForeignKey(db_column='band_id', on_delete=django.db.models.deletion.CASCADE, related_name='album_by_band', to='tracks.band'),
        ),
    ]
