# Generated by Django 4.0.1 on 2022-01-28 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='band_id',
            field=models.ForeignKey(db_column='band_id', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='tracks.band'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album_id',
            field=models.ForeignKey(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='tracks.album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='band_id',
            field=models.ForeignKey(db_column='band_id', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='tracks.band'),
        ),
    ]
