# Generated by Django 4.0.1 on 2022-01-30 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_alter_album_band_id_alter_track_album_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('band_name', 'album_release_date', 'album_name'), 'verbose_name': 'Альбомы', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ('band_name',), 'verbose_name': 'Группы', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('band_name', 'album_name', 'track_name'), 'verbose_name': 'Треки', 'verbose_name_plural': 'Треки'},
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('band_id', models.CharField(max_length=255)),
                ('band_name', models.CharField(max_length=255)),
                ('album_id', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('track_name', models.CharField(max_length=255)),
                ('text_created', models.DateTimeField(auto_now_add=True)),
                ('track_id', models.ForeignKey(db_column='track_id', on_delete=django.db.models.deletion.CASCADE, to='tracks.track')),
            ],
            options={
                'verbose_name': 'Тексты песен',
                'verbose_name_plural': 'Тексты песен',
                'ordering': ('band_name', 'album_name', 'track_name'),
            },
        ),
    ]
