# Generated by Django 4.0.1 on 2022-01-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_alter_album_options_alter_band_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='text_slug',
        ),
    ]
