# Generated by Django 4.0.1 on 2022-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_remove_text_text_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='song_text',
            field=models.TextField(null=True),
        ),
    ]
