# Generated by Django 4.0.1 on 2022-01-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_text_song_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='text_slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
